### ISSUE TITLE
Can you publish compiled releases ?

### ISSUE THREAD

**Issue by dragonofmercy** [Viomi/modorganizer-game_skyrim_se#8]
Can you publish compiled releases ?

**Comment by Nerezza** [comment]
Mod Organizer was made in an incredibly-difficult-to-compile way. Although it's been a day or two since this repo opened, it seems Viomi is still struggling to get just one compile done so there isn't anything to publish yet.

**Comment by Viomi** [comment]
@zellerda As soon as I can get it to compile, I'll release it.
